server:
  port: 8882
eureka:
  client:
#    registryWithEureka: true
#    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8881/eureka/
#    instance:
#      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ws-historico
          uri: http://localhost:8087/historicos
          predicates:
            - Path=/historicos/**
        - id: ws-customer
          uri: http://localhost:8083/customers
          predicates:
            - Path=/customers/**
        - id: ws-product
          uri: http://localhost:8084/products
          predicates:
            - Path=/products/**    
  #application:
  #  name: registry-service          