
server:
  port: 8882
eureka:
  client:
#    registryWithEureka: true
#    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8881/eureka/
#    instance:
#      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ws-historico
          uri: http://localhost:8882/api/v1/historicos
#          uri: lb//ws-producto
          predicates:
            - Path=/api/v1/historicos/**
  #application:
  #  name: registry-service          